### ISSUE TITLE
f!skips skips two songs

### ISSUE THREAD

**Issue by xmatmen** [xmatmen/fbot#10]
I'm clueless what's causing this, but `f!skip` skips two songs like 80% of the time. This only happens on Linux and might be a `discord.js` or `ytdl` issue, however i cant be 100% sure that it isnt fbot's code.  
This only happens when you call `VoiceDispatcher#end()`, not if the VoiceDispatcher ends naturally. If you call `VoiceDispatcher#end()`, the next `VoiceDispatcher` just ends instantly.  
Code at [commands/play](https://github.com/xmatmen/fbot/blob/master/commands/voice/play.js) (and maybe also [commands/skip](https://github.com/xmatmen/fbot/blob/master/commands/voice/skip.js)?)

**Comment by level6ascend** [comment]
ha

**Comment by emptixo** [comment]
No u
